# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.order_response import OrderResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestOrderResponse(unittest.TestCase):
    """OrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OrderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.order_response.OrderResponse()  # noqa: E501
        if include_optional :
            return OrderResponse(
                client_request_id = '30dd879c-ee2f-11db-8314-0800200c9a66', 
                api_trace_id = 'rrt-0bd552c12342d3448-b-ea-1142-12938318-7', 
                response_type = 'Unauthenticated', 
                order_id = '123456', 
                billing = {"name":"John Doe","customerId":"1234567890","address":{"address1":"123 Main St.","city":"Sandy Springs","region":"Georgia","postalCode":"30303","country":"USA"}}, 
                shipping = {"name":"John Doe","contact":{"phone":"5555555555","mobilePhone":"5555555555","email":"john@test.com"},"address":{"address1":"123 Main St.","city":"Sandy Springs","region":"Georgia","postalCode":"30303","country":"USA"}}, 
                transactions = [{"transactionState":"AUTHORIZED","ipgTransactionId":"838916029301","transactionType":"SALE","transactionAmount":{"total":10.24,"currency":"USD"},"storeId":"1109959991"}], 
                additional_details = {"comments":"This is a comment","invoiceNumber":"551294633441","purchaseOrderNumber":"1223456","operatorId":"OPERATOR_ID_123XXX","salesSystemId":"W-EU-H3866-FLS2","ipgDeferredAuth":true,"highRiskPurchaseIndicator":true}
            )
        else :
            return OrderResponse(
        )

    def testOrderResponse(self):
        """Test OrderResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
