# coding: utf-8

"""
    Payment Gateway API Specification

    Payment Gateway API for payment processing.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.payment_api import PaymentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentApi(unittest.TestCase):
    """PaymentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.payment_api.PaymentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perform_payment_post_authorisation(self):
        """Test case for perform_payment_post_authorisation

        Use this to capture/complete a transaction. Partial postauths are allowed.  # noqa: E501
        """
        pass

    def test_primary_payment_transaction(self):
        """Test case for primary_payment_transaction

        Generate a primary transaction  # noqa: E501
        """
        pass

    def test_return_transaction(self):
        """Test case for return_transaction

        Return/refund a transaction.  # noqa: E501
        """
        pass

    def test_transaction_inquiry(self):
        """Test case for transaction_inquiry

        Retrieve the state of a transaction  # noqa: E501
        """
        pass

    def test_void_transaction(self):
        """Test case for void_transaction

        Reverse a previous action on an existing transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
