# coding: utf-8

"""
    Payment Gateway API Specification.

    Payment Gateway API for payment processing. Version 6.4.0.20181018.001   # noqa: E501

    OpenAPI spec version: 6.4.0.20181018.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.access_token_response import AccessTokenResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestAccessTokenResponse(unittest.TestCase):
    """AccessTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessTokenResponse(self):
        """Test AccessTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.access_token_response.AccessTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
