# coding: utf-8

"""
    Payment Gateway API Specification

    Payment Gateway API for payment processing.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.industry_specific_extensions import IndustrySpecificExtensions  # noqa: E501
from swagger_client.rest import ApiException


class TestIndustrySpecificExtensions(unittest.TestCase):
    """IndustrySpecificExtensions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndustrySpecificExtensions(self):
        """Test IndustrySpecificExtensions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.industry_specific_extensions.IndustrySpecificExtensions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
