# coding: utf-8

"""
    Payment Gateway API Specification

    Payment Gateway API for payment processing.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transaction_response_authentication_redirect import TransactionResponseAuthenticationRedirect  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionResponseAuthenticationRedirect(unittest.TestCase):
    """TransactionResponseAuthenticationRedirect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionResponseAuthenticationRedirect(self):
        """Test TransactionResponseAuthenticationRedirect"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transaction_response_authentication_redirect.TransactionResponseAuthenticationRedirect()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
