# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.tele_check_ach_payment_method_ach_bill_to import TeleCheckAchPaymentMethodAchBillTo  # noqa: E501
from openapi_client.rest import ApiException

class TestTeleCheckAchPaymentMethodAchBillTo(unittest.TestCase):
    """TeleCheckAchPaymentMethodAchBillTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TeleCheckAchPaymentMethodAchBillTo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.tele_check_ach_payment_method_ach_bill_to.TeleCheckAchPaymentMethodAchBillTo()  # noqa: E501
        if include_optional :
            return TeleCheckAchPaymentMethodAchBillTo(
                first_name = 'R2-D2', 
                last_name = 'O'Calloway', 
                address_one = '1234 Line Ave S.', 
                address_two = 'Ste 602', 
                city = 'Atlanta', 
                state = 'GA', 
                zip = '30040-1309', 
                phone = '9973322990', 
                email = 'abcd.1234@fiserv.com', 
                country_code = 'US'
            )
        else :
            return TeleCheckAchPaymentMethodAchBillTo(
                last_name = 'O'Calloway',
                address_one = '1234 Line Ave S.',
                city = 'Atlanta',
                state = 'GA',
                zip = '30040-1309',
                phone = '9973322990',
        )

    def testTeleCheckAchPaymentMethodAchBillTo(self):
        """Test TeleCheckAchPaymentMethodAchBillTo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
