# coding: utf-8

"""
    Payment Gateway API Specification.

    Payment Gateway API for payment processing. Version 6.4.0.20181018.001   # noqa: E501

    OpenAPI spec version: 6.4.0.20181018.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.purchase_cards_level3 import PurchaseCardsLevel3  # noqa: E501
from openapi_client.rest import ApiException


class TestPurchaseCardsLevel3(unittest.TestCase):
    """PurchaseCardsLevel3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPurchaseCardsLevel3(self):
        """Test PurchaseCardsLevel3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.purchase_cards_level3.PurchaseCardsLevel3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
