# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.9.1.20191223.002
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.payment_token_credit_transaction_all_of import PaymentTokenCreditTransactionAllOf  # noqa: E501
from openapi_client.rest import ApiException


class TestPaymentTokenCreditTransactionAllOf(unittest.TestCase):
    """PaymentTokenCreditTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentTokenCreditTransactionAllOf(self):
        """Test PaymentTokenCreditTransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.payment_token_credit_transaction_all_of.PaymentTokenCreditTransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
