# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.recurring_payment_details import RecurringPaymentDetails  # noqa: E501
from openapi_client.rest import ApiException

class TestRecurringPaymentDetails(unittest.TestCase):
    """RecurringPaymentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RecurringPaymentDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.recurring_payment_details.RecurringPaymentDetails()  # noqa: E501
        if include_optional :
            return RecurringPaymentDetails(
                store_id = '1109959991', 
                purchase_order_number = '123055342', 
                invoice_number = '96126098', 
                creation_date = '2018-10-25', 
                start_date = '2018-10-25', 
                next_attempt_date = '2018-10-25', 
                transaction_amount = {"total":10.24,"currency":"USD","components":{"subtotal":8.0,"localTax":1.0,"shipping":1.24}}, 
                payment_method_details = {"paymentCard":{"number":"5424180279791732","expiryDate":{"month":"03","year":"21"},"securityCode":"977"},"paymentMethodType":"PAYMENT_CARD"}, 
                frequency = {"every":3,"unit":"DAY"}, 
                number_of_payments = 10, 
                run_count = 10, 
                state = 'Installed', 
                comments = 'This scheduled payment series is to pay for the thing.'
            )
        else :
            return RecurringPaymentDetails(
        )

    def testRecurringPaymentDetails(self):
        """Test RecurringPaymentDetails"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
