# coding: utf-8

"""
    Payment Gateway API Specification

    Payment Gateway API for payment processing.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transaction_type import TransactionType  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionType(unittest.TestCase):
    """TransactionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionType(self):
        """Test TransactionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transaction_type.TransactionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
