# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.payment_device_pre_auth_transaction_all_of import PaymentDevicePreAuthTransactionAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestPaymentDevicePreAuthTransactionAllOf(unittest.TestCase):
    """PaymentDevicePreAuthTransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaymentDevicePreAuthTransactionAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.payment_device_pre_auth_transaction_all_of.PaymentDevicePreAuthTransactionAllOf()  # noqa: E501
        if include_optional :
            return PaymentDevicePreAuthTransactionAllOf(
                payment_method = {"paymentDevice":{"deviceType":"SWIPE","data":"02A600C0170018008292;5424********1732=1810?*B73CD8C26233D4FFEC5500ED394439D97DDA5F530942D21D0000000000000000000000000000000000000000363434543035353734326299492410027300000260DC03","securityCode":"977","cardholderName":"First Cardholder","cardFunction":"CREDIT","brand":"VISA"},"paymentFacilitator":{"externalMerchantId":"12345","paymentFacilitatorId":"123123123","saleOrganizationId":"123124214","name":"First Reseller","subMerchantData":{"mcc":"1432","legalName":"First Merchant","timezone":"Europe/London","address":{"address1":"123 Main St.","city":"Sandy Springs","region":"Georgia","postalCode":"30303","country":"USA"},"document":{"type":"NATIONAL_IDENTITY","number":"12345666544"},"merchantId":"12435325235"}}}, 
                create_token = {"value":"234ljl124l12","reusable":true,"declineDuplicates":false}, 
                settlement_split = [{"merchantID":"100000001","amount":25.06},{"merchantID":"100000002","amount":15.07}], 
                stored_credentials = {"sequence":"SUBSEQUENT","scheduled":false,"referencedSchemeTransactionId":"019087868716215","initiator":"CARDHOLDER"}, 
                split_shipment = {"totalCount":1,"finalShipment":true}, 
                decremental_flag = False
            )
        else :
            return PaymentDevicePreAuthTransactionAllOf(
                payment_method = {"paymentDevice":{"deviceType":"SWIPE","data":"02A600C0170018008292;5424********1732=1810?*B73CD8C26233D4FFEC5500ED394439D97DDA5F530942D21D0000000000000000000000000000000000000000363434543035353734326299492410027300000260DC03","securityCode":"977","cardholderName":"First Cardholder","cardFunction":"CREDIT","brand":"VISA"},"paymentFacilitator":{"externalMerchantId":"12345","paymentFacilitatorId":"123123123","saleOrganizationId":"123124214","name":"First Reseller","subMerchantData":{"mcc":"1432","legalName":"First Merchant","timezone":"Europe/London","address":{"address1":"123 Main St.","city":"Sandy Springs","region":"Georgia","postalCode":"30303","country":"USA"},"document":{"type":"NATIONAL_IDENTITY","number":"12345666544"},"merchantId":"12435325235"}}},
        )

    def testPaymentDevicePreAuthTransactionAllOf(self):
        """Test PaymentDevicePreAuthTransactionAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
