# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.clearing_details import ClearingDetails  # noqa: E501
from openapi_client.rest import ApiException

class TestClearingDetails(unittest.TestCase):
    """ClearingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClearingDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.clearing_details.ClearingDetails()  # noqa: E501
        if include_optional :
            return ClearingDetails(
                clearing_elements = [{"clearingElement":{"brand":"VISA","value":"1234","count":"1234"}},{"clearingElement":{"brand":"AMEX","value":"4321","count":"999"}}], 
                batch_time_stamp = '20190501094321', 
                receipt_number_from = 2520, 
                receipt_number_to = 2567, 
                trace_number = 113744
            )
        else :
            return ClearingDetails(
        )

    def testClearingDetails(self):
        """Test ClearingDetails"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
