# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.encrypted_samsung_pay_wallet_payment_method import EncryptedSamsungPayWalletPaymentMethod  # noqa: E501
from openapi_client.rest import ApiException

class TestEncryptedSamsungPayWalletPaymentMethod(unittest.TestCase):
    """EncryptedSamsungPayWalletPaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EncryptedSamsungPayWalletPaymentMethod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.encrypted_samsung_pay_wallet_payment_method.EncryptedSamsungPayWalletPaymentMethod()  # noqa: E501
        if include_optional :
            return EncryptedSamsungPayWalletPaymentMethod(
                wallet_type = 'EncryptedApplePayWalletPaymentMethod', 
                encrypted_samsung_pay = {"data":"eyJhbGciOiJSU0ExXzUiLCJraWQiOiJadDRZQ0dpRVMvU2F0RGtuampsdnhxNmdNUTRDK1lvcFJUanJtTDBlRldZPSIsInR5cCI6IkpPU0UiLCJjaGFubmVsU2VjdXJpdHlDb250ZXh0IjoiUlNBX1BLSSIsImVuYyI6IkExMjhHQ00ifQ","version":"100"}
            )
        else :
            return EncryptedSamsungPayWalletPaymentMethod(
                wallet_type = 'EncryptedApplePayWalletPaymentMethod',
                encrypted_samsung_pay = {"data":"eyJhbGciOiJSU0ExXzUiLCJraWQiOiJadDRZQ0dpRVMvU2F0RGtuampsdnhxNmdNUTRDK1lvcFJUanJtTDBlRldZPSIsInR5cCI6IkpPU0UiLCJjaGFubmVsU2VjdXJpdHlDb250ZXh0IjoiUlNBX1BLSSIsImVuYyI6IkExMjhHQ00ifQ","version":"100"},
        )

    def testEncryptedSamsungPayWalletPaymentMethod(self):
        """Test EncryptedSamsungPayWalletPaymentMethod"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
