# coding: utf-8

"""
    Payment Gateway API Specification.

    Payment Gateway API for payment processing. Version 6.4.0.20181018.001   # noqa: E501

    OpenAPI spec version: 6.4.0.20181018.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.amount_components import AmountComponents  # noqa: E501
from openapi_client.rest import ApiException


class TestAmountComponents(unittest.TestCase):
    """AmountComponents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmountComponents(self):
        """Test AmountComponents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.amount_components.AmountComponents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
