# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.airline import Airline  # noqa: E501
from openapi_client.rest import ApiException

class TestAirline(unittest.TestCase):
    """Airline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Airline
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.airline.Airline()  # noqa: E501
        if include_optional :
            return Airline(
                passenger_name = 'Jeff Yabuki', 
                ticket_number = '52300448', 
                issuing_carrier = 'Frontier Airlines', 
                carrier_name = 'Delta Air Lines', 
                travel_agency_iata_code = '10584410', 
                travel_agency_name = 'A Travis Gent LLC', 
                airline_plan_number = '11', 
                airline_invoice_number = '664422', 
                reservation_system = 'DELTA', 
                restricted = True, 
                travel_route = [{"departureDate":"2018-01-28","origin":"MIA","destination":"ATL","carrierCode":"DL","serviceClass":"J","stopoverType":"DIRECT","fareBasisCode":"F","departureTax":75,"flightNumber":"765599"}], 
                related_ticket_number = '11223344556', 
                ancillary_service_category = [{"serviceCategory":"BAGGAGE_FEE"},{"serviceCategory":"CARBON_OFFSET"}], 
                ticket_purchase = True
            )
        else :
            return Airline(
        )

    def testAirline(self):
        """Test Airline"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
