# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.payment_device_payment_tokenization_request_all_of import PaymentDevicePaymentTokenizationRequestAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestPaymentDevicePaymentTokenizationRequestAllOf(unittest.TestCase):
    """PaymentDevicePaymentTokenizationRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaymentDevicePaymentTokenizationRequestAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.payment_device_payment_tokenization_request_all_of.PaymentDevicePaymentTokenizationRequestAllOf()  # noqa: E501
        if include_optional :
            return PaymentDevicePaymentTokenizationRequestAllOf(
                payment_device = {"deviceType":"SWIPE","data":"02A600C0170018008292;5424********1732=1810?*B73CD8C26233D4FFEC5500ED394439D97DDA5F530942D21D0000000000000000000000000000000000000000363434543035353734326299492410027300000260DC03","securityCode":"977"}
            )
        else :
            return PaymentDevicePaymentTokenizationRequestAllOf(
                payment_device = {"deviceType":"SWIPE","data":"02A600C0170018008292;5424********1732=1810?*B73CD8C26233D4FFEC5500ED394439D97DDA5F530942D21D0000000000000000000000000000000000000000363434543035353734326299492410027300000260DC03","securityCode":"977"},
        )

    def testPaymentDevicePaymentTokenizationRequestAllOf(self):
        """Test PaymentDevicePaymentTokenizationRequestAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
