# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.9.1.20191223.002
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.payment_card_payment_tokenization_request_all_of import PaymentCardPaymentTokenizationRequestAllOf  # noqa: E501
from openapi_client.rest import ApiException


class TestPaymentCardPaymentTokenizationRequestAllOf(unittest.TestCase):
    """PaymentCardPaymentTokenizationRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentCardPaymentTokenizationRequestAllOf(self):
        """Test PaymentCardPaymentTokenizationRequestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.payment_card_payment_tokenization_request_all_of.PaymentCardPaymentTokenizationRequestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
