# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.secure3_d10_authentication_update_request import Secure3D10AuthenticationUpdateRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestSecure3D10AuthenticationUpdateRequest(unittest.TestCase):
    """Secure3D10AuthenticationUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Secure3D10AuthenticationUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.secure3_d10_authentication_update_request.Secure3D10AuthenticationUpdateRequest()  # noqa: E501
        if include_optional :
            return Secure3D10AuthenticationUpdateRequest(
                store_id = '12345500000', 
                authentication_type = 'Secure3D10AuthenticationUpdateRequest', 
                billing_address = {"address1":"123 Main St.","city":"Sandy Springs","region":"Georgia","postalCode":"30303","country":"USA"}, 
                payer_authentication_response = 'eJzVWFm....9f/AhjgEcE=', 
                merchant_data = 'MD__________30002019....85bcd02599', 
                security_code = '123'
            )
        else :
            return Secure3D10AuthenticationUpdateRequest(
                authentication_type = 'Secure3D10AuthenticationUpdateRequest',
                payer_authentication_response = 'eJzVWFm....9f/AhjgEcE=',
                merchant_data = 'MD__________30002019....85bcd02599',
        )

    def testSecure3D10AuthenticationUpdateRequest(self):
        """Test Secure3D10AuthenticationUpdateRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
