# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.9.1.20191223.002
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.sub_merchant_data import SubMerchantData  # noqa: E501
from openapi_client.rest import ApiException


class TestSubMerchantData(unittest.TestCase):
    """SubMerchantData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubMerchantData(self):
        """Test SubMerchantData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.sub_merchant_data.SubMerchantData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
