# coding: utf-8

"""
    Payment Gateway API Specification.

    The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.  # noqa: E501

    The version of the OpenAPI document: 6.12.0.20200605.001
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.fraud_order import FraudOrder  # noqa: E501
from openapi_client.rest import ApiException

class TestFraudOrder(unittest.TestCase):
    """FraudOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FraudOrder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.fraud_order.FraudOrder()  # noqa: E501
        if include_optional :
            return FraudOrder(
                ship_to_address = {"phone":"404-404-4040","address1":"5565 Glenridge Connector","city":"Atlanta","state":"GA","zip":"30342","country":"US"}, 
                items = [{"id":"PRODCODE1","name":"The Art of Computer Programming","quantity":"litre","unit":10.23,"unitPrice":{"value":7300,"currency":"USD"},"categories":"[[\"Books\", \"Computers & Technology\", \"Programming\"], [\"Books\", \"Text Books\", \"Computer Science\"]]","detailsUrl":"https://mystore.domain/product/PRODCODE1","userDefined":{"weight":5021.23,"vat":0.06}}], 
                user_defined = {"delivery":"express","carrier":"ups"}
            )
        else :
            return FraudOrder(
        )

    def testFraudOrder(self):
        """Test FraudOrder"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
