# coding: utf-8

"""
    Payment Gateway API Specification.

    Payment Gateway API for payment processing. Version 6.4.0.20181018.001   # noqa: E501

    OpenAPI spec version: 6.4.0.20181018.001
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ReferencedOrder(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'order_id': 'str',
        'payment_tokenization': 'PaymentTokenization'
    }

    attribute_map = {
        'order_id': 'orderId',
        'payment_tokenization': 'paymentTokenization'
    }

    def __init__(self, order_id=None, payment_tokenization=None):  # noqa: E501
        """ReferencedOrder - a model defined in OpenAPI"""  # noqa: E501

        self._order_id = None
        self._payment_tokenization = None
        self.discriminator = None

        if order_id is not None:
            self.order_id = order_id
        if payment_tokenization is not None:
            self.payment_tokenization = payment_tokenization

    @property
    def order_id(self):
        """Gets the order_id of this ReferencedOrder.  # noqa: E501

        Use this to retrieve the payment instrument information from an existing Order  # noqa: E501

        :return: The order_id of this ReferencedOrder.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this ReferencedOrder.

        Use this to retrieve the payment instrument information from an existing Order  # noqa: E501

        :param order_id: The order_id of this ReferencedOrder.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def payment_tokenization(self):
        """Gets the payment_tokenization of this ReferencedOrder.  # noqa: E501


        :return: The payment_tokenization of this ReferencedOrder.  # noqa: E501
        :rtype: PaymentTokenization
        """
        return self._payment_tokenization

    @payment_tokenization.setter
    def payment_tokenization(self, payment_tokenization):
        """Sets the payment_tokenization of this ReferencedOrder.


        :param payment_tokenization: The payment_tokenization of this ReferencedOrder.  # noqa: E501
        :type: PaymentTokenization
        """

        self._payment_tokenization = payment_tokenization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReferencedOrder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
